INSERT INTO detail_type (Name, Description) VALUES
	('BG_start_ms','Background start in ms'),
	('BG_stop_ms','Background stop in ms'),
	('BG_chan_label','Background channel label'),
	('MR_start_ms','M-response start in ms'),
	('MR_stop_ms','M-response start in ms'),
	('MR_chan_label','M-response channel label'),
	('HR_start_ms','H-reflex start in ms'),
	('HR_stop_ms','H-reflex start in ms'),
	('HR_chan_label','H-reflex channel label'),
	('HR_detection_limit','Min HR size for true detection'),
	('Nerve_stim_output','Nerve stimulator output intensity'),
	('MEP_start_ms','MEP start in ms'),
	('MEP_stop_ms','MEP start in ms'),
	('MEP_chan_label','MEP channel label'),
	('MEP_detection_limit','Min MEP size for true detection'),
	('TMS_powerA','Stimulator output in pcnt'),
	('TMS_powerB','Second pulse intensity in Bistim'),
	('TMS_ISI_ms','Bistim inter-stim interval in ms'),
	('TMS_coil_x','Coil x-coordinate in mm'),
	('TMS_coil_y','Coil y-coordinate in mm'),
	('TMS_coil_z','Coil z-coordinate in mm'),
	('TMS_coil_rot','Coil rotation in deg'),
	('Task_condition','Which task was used this trial? (e.g. 0 or 1)'),
	('Task_start_ms','Task analysis window start in ms'),
	('Task_stop_ms','Task analysis window stop in ms'),
	('Conditioned_feature_name','feature_type.name of conditioned feature'),
	('Conditioned_result','Whether the conditioned feature was rewarded');