# Generated by Django 4.0.4 on 2022-05-02 16:30

from django.db import migrations, models
import serf.models


class Migration(migrations.Migration):

    dependencies = [
        ('serf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='name',
        ),
        migrations.AddField(
            model_name='procedure',
            name='offset_direction',
            field=serf.models.EnumField(choices=[('none', 'none'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H')], default='none', max_length=104),
        ),
        migrations.AddField(
            model_name='procedure',
            name='offset_size',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='procedure',
            name='target_name',
            field=models.CharField(blank=True, max_length=135),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='type',
            field=serf.models.EnumField(choices=[('none', 'none'), ('DBS', 'DBS'), ('surgical', 'surgical'), ('experiment', 'experiment'), ('monitoring', 'monitoring'), ('other', 'other')], default='none', max_length=104),
        ),
    ]
