# Generated by Django 2.2.6 on 2019-11-23 07:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
import eerfapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datum',
            fields=[
                ('datum_id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(default=0)),
                ('span_type', eerfapp.models.EnumField(choices=[('trial', 'trial'), ('day', 'day'), ('period', 'period')], max_length=104)),
                ('is_good', models.BooleanField(default=True)),
                ('start_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('stop_time', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'datum',
            },
        ),
        migrations.CreateModel(
            name='DatumFeatureValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True)),
                ('datum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_feature_values', to='eerfapp.Datum')),
            ],
            options={
                'db_table': 'datum_feature_value',
            },
        ),
        migrations.CreateModel(
            name='DetailType',
            fields=[
                ('detail_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=135, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'db_table': 'detail_type',
            },
        ),
        migrations.CreateModel(
            name='FeatureType',
            fields=[
                ('feature_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=135, unique=True)),
                ('description', models.CharField(blank=True, max_length=135)),
            ],
            options={
                'db_table': 'feature_type',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=135, unique=True)),
                ('id', models.CharField(blank=True, max_length=135, null=True)),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('headsize', models.CharField(blank=True, max_length=135, null=True)),
                ('sex', eerfapp.models.EnumField(choices=[('unknown', 'unknown'), ('male', 'male'), ('female', 'female'), ('unspecified', 'unspecified')], max_length=104)),
                ('handedness', eerfapp.models.EnumField(choices=[('unknown', 'unknown'), ('right', 'right'), ('left', 'left'), ('equal', 'equal')], max_length=104)),
                ('smoking', eerfapp.models.EnumField(choices=[('unknown', 'unknown'), ('no', 'no'), ('yes', 'yes')], max_length=104)),
                ('alcohol_abuse', eerfapp.models.EnumField(choices=[('unknown', 'unknown'), ('no', 'no'), ('yes', 'yes')], max_length=104)),
                ('drug_abuse', eerfapp.models.EnumField(choices=[('unknown', 'unknown'), ('no', 'no'), ('yes', 'yes')], max_length=104)),
                ('medication', eerfapp.models.EnumField(choices=[('unknown', 'unknown'), ('no', 'no'), ('yes', 'yes')], max_length=104)),
                ('visual_impairment', eerfapp.models.EnumField(choices=[('unknown', 'unknown'), ('no', 'no'), ('yes', 'yes'), ('corrected', 'corrected')], max_length=104)),
                ('heart_impairment', eerfapp.models.EnumField(choices=[('unknown', 'unknown'), ('no', 'no'), ('yes', 'yes'), ('pacemaker', 'pacemaker')], max_length=104)),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('name', models.CharField(max_length=135, primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=135)),
            ],
            options={
                'db_table': 'system',
            },
        ),
        migrations.CreateModel(
            name='DatumFeatureStore',
            fields=[
                ('dfv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='store', serialize=False, to='eerfapp.DatumFeatureValue')),
                ('x_vec', eerfapp.models.NPArrayBlobField(blank=True, null=True)),
                ('dat_array', eerfapp.models.NPArrayBlobField(blank=True, null=True)),
                ('n_channels', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('n_features', models.PositiveIntegerField(blank=True, null=True)),
                ('channel_labels', eerfapp.models.CSVStringField(blank=True, null=True)),
            ],
            options={
                'db_table': 'datum_feature_value_store',
            },
        ),
        migrations.CreateModel(
            name='DatumStore',
            fields=[
                ('datum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='store', serialize=False, to='eerfapp.Datum')),
                ('x_vec', eerfapp.models.NPArrayBlobField(blank=True, null=True)),
                ('erp', eerfapp.models.NPArrayBlobField(blank=True, null=True)),
                ('n_channels', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('n_samples', models.PositiveIntegerField(blank=True, null=True)),
                ('channel_labels', eerfapp.models.CSVStringField(blank=True, null=True)),
            ],
            options={
                'db_table': 'datum_store',
            },
        ),
        migrations.CreateModel(
            name='SubjectLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('entry', models.TextField(blank=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eerfapp.Subject')),
            ],
            options={
                'db_table': 'subject_log',
            },
        ),
        migrations.AddField(
            model_name='datumfeaturevalue',
            name='feature_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eerfapp.FeatureType'),
        ),
        migrations.AddField(
            model_name='datum',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='eerfapp.Subject'),
        ),
        migrations.AddField(
            model_name='datum',
            name='trials',
            field=models.ManyToManyField(db_table='datum_has_datum', limit_choices_to={'span_type': 'trial'}, related_name='periods', to='eerfapp.Datum'),
        ),
        migrations.CreateModel(
            name='SubjectDetailValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=135, null=True)),
                ('detail_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eerfapp.DetailType')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_detail_values', to='eerfapp.Subject')),
            ],
            options={
                'db_table': 'subject_detail_value',
                'unique_together': {('subject', 'detail_type')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='datumfeaturevalue',
            unique_together={('datum', 'feature_type')},
        ),
        migrations.CreateModel(
            name='DatumDetailValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=135, null=True)),
                ('datum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_detail_values', to='eerfapp.Datum')),
                ('detail_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eerfapp.DetailType')),
            ],
            options={
                'db_table': 'datum_detail_value',
                'unique_together': {('datum', 'detail_type')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='datum',
            unique_together={('subject', 'number', 'span_type')},
        ),
    ]
